using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

namespace ChambaIA.Infrastructure.Resumes;

public sealed class ResumeStorageOptions
{
    public const string Section = "Storage";

    /// <summary>Folder for uploaded CVs. Relative paths resolve from the app's content root. Never inside a web-served folder.</summary>
    public string ResumesPath { get; set; } = "storage/resumes";
}

public interface IResumeStorage
{
    /// <summary>Stores the bytes under a random name and returns the storage key (never derived from user input).</summary>
    Task<string> SaveAsync(byte[] content, string extension, CancellationToken ct);
    Task DeleteAsync(string key);
}

public sealed class LocalResumeStorage(IOptions<ResumeStorageOptions> options, IHostEnvironment env) : IResumeStorage
{
    private string Root => Path.IsPathRooted(options.Value.ResumesPath)
        ? options.Value.ResumesPath
        : Path.Combine(env.ContentRootPath, options.Value.ResumesPath);

    public async Task<string> SaveAsync(byte[] content, string extension, CancellationToken ct)
    {
        Directory.CreateDirectory(Root);
        var key = $"{Guid.NewGuid():N}{extension}";
        await File.WriteAllBytesAsync(Path.Combine(Root, key), content, ct);
        return key;
    }

    public Task DeleteAsync(string key)
    {
        // Keys are generated by us; still refuse anything that is not a bare file name.
        if (key != Path.GetFileName(key) || key.Length == 0) return Task.CompletedTask;
        var path = Path.Combine(Root, key);
        if (File.Exists(path)) File.Delete(path);
        return Task.CompletedTask;
    }
}
